"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { AppShell } from "../components/app-shell";
import { api, getBusinessId } from "../lib/api";
import type { BusinessStats, ActivityEvent } from "../lib/api";

export default function Home() {
  const [period, setPeriod] = useState<"This week" | "Last week">("This week");
  const [apiState, setApiState] = useState<"checking" | "online" | "offline">("checking");
  const [stats, setStats] = useState<BusinessStats | null>(null);
  const [activity, setActivity] = useState<ActivityEvent[]>([]);
  const [showAllActivity, setShowAllActivity] = useState(false);
  const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000/api";
  const router = useRouter();

  useEffect(() => {
    if (typeof window !== "undefined" && !localStorage.getItem("relay_token")) router.replace("/login");
  }, [router]);

  useEffect(() => {
    const bizId = getBusinessId();
    if (!bizId) return;
    api.businesses.stats(bizId).then(setStats).catch(console.error);
  }, []);

  useEffect(() => {
    const bizId = getBusinessId();
    if (!bizId) return;
    api.businesses.activity(bizId, showAllActivity ? 100 : 20).then(setActivity).catch(console.error);
  }, [showAllActivity]);

  useEffect(() => {
    async function connect() {
      try {
        const health = await fetch(`${apiUrl}/health`);
        if (!health.ok) throw new Error("API unavailable");
        setApiState("online");
      } catch {
        setApiState("offline");
      }
    }
    void connect();
  }, [apiUrl]);

  function fmtRevenue(v: string | number) {
    const n = Number(v ?? 0);
    if (n >= 100000) return `₹${(n / 100000).toFixed(2)}L`;
    return `₹${n.toLocaleString("en-IN")}`;
  }

  const thisWeek = Number(stats?.revenueThisWeek ?? 0);
  const lastWeek = Number(stats?.revenueLastWeek ?? 0);
  const periodRevenue = period === "This week" ? thisWeek : lastWeek;
  const periodChangePct = lastWeek > 0 ? ((thisWeek - lastWeek) / lastWeek) * 100 : null;

  return (
    <AppShell title="Overview" subtitle="Here's how your AI sales team is performing." action={<button className="primary-button" onClick={() => router.push("/automations")}><span>＋</span> Create automation</button>}>
      <p className={`api-status ${apiState}`}><i /> {apiState === "checking" ? "Connecting to your API…" : apiState === "online" ? "API connected" : "API offline — start the backend to enable live data"}</p>

      <div className="metric-grid">
        <article className="metric-card"><div className="metric-header"><span className="metric-icon peach">✦</span><button onClick={() => router.push("/leads")}>View</button></div><p>New leads</p><h2>{stats?.leads ?? "—"}</h2></article>
        <article className="metric-card"><div className="metric-header"><span className="metric-icon purple">◌</span><button onClick={() => router.push("/inbox")}>View</button></div><p>Conversations</p><h2>{stats?.conversations ?? "—"}</h2></article>
        <article className="metric-card"><div className="metric-header"><span className="metric-icon blue">↗</span><button onClick={() => router.push("/orders")}>View</button></div><p>Orders</p><h2>{stats?.orders ?? "—"}</h2></article>
        <article className="metric-card revenue"><div className="metric-header"><span className="metric-icon yellow">₹</span><button onClick={() => router.push("/orders")}>View</button></div><p>Revenue (paid orders)</p><h2>{stats ? fmtRevenue(stats.revenue) : "—"}</h2></article>
      </div>

      <div className="dashboard-grid">
        <article className="card performance-card">
          <div className="card-heading"><div><h3>Sales performance</h3><p>Revenue generated by your AI agent</p></div><button className="select" onClick={() => setPeriod(period === "This week" ? "Last week" : "This week")}>{period} <i>⌄</i></button></div>
          <div className="chart-wrap"><div className="chart-y"><span>₹5L</span><span>₹4L</span><span>₹3L</span><span>₹2L</span><span>₹1L</span><span>₹0</span></div><div className="chart"><div className="gridlines"/><svg className="line-chart" viewBox="0 0 620 198" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#8267df" stopOpacity=".26"/><stop offset="1" stopColor="#8267df" stopOpacity="0"/></linearGradient></defs><path d="M0 168 C40 152 44 141 77 148 S118 153 139 136 S168 109 200 125 S237 158 263 142 S295 111 324 118 S353 142 385 120 S421 78 449 98 S486 139 511 100 S548 47 574 66 S600 92 620 31 L620 198 L0 198Z" fill="url(#fill)"/><path d="M0 168 C40 152 44 141 77 148 S118 153 139 136 S168 109 200 125 S237 158 263 142 S295 111 324 118 S353 142 385 120 S421 78 449 98 S486 139 511 100 S548 47 574 66 S600 92 620 31" fill="none" stroke="#7961d5" strokeWidth="3"/></svg><div className="chart-labels"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div></div>
          <div className="chart-summary"><div><span className="dot purple-dot"/> Revenue <strong>{stats ? fmtRevenue(periodRevenue) : "—"}</strong></div><span>{periodChangePct === null ? "No data" : `${periodChangePct >= 0 ? "+" : ""}${periodChangePct.toFixed(1)}%`} <b>from last week</b></span></div>
        </article>

        <article className="card agent-card"><div className="agent-orb"><span>✦</span></div><p className="live"><i /> AI agent is active</p><h3>Your agent is on it.</h3><p className="agent-copy">It's currently managing {stats?.openConversations ?? 0} open conversations.</p><div className="agent-list"><div><span className="round-icon">✉</span><p><strong>{stats?.openConversations ?? 0} conversations</strong><small>are waiting for a reply</small></p><button onClick={() => router.push("/inbox")}>Review</button></div><div><span className="round-icon pink">♨</span><p><strong>{stats?.leads ?? 0} leads</strong><small>need your attention</small></p><button onClick={() => router.push("/leads")}>View</button></div></div><button className="agent-button" onClick={() => router.push("/automations")}>View agent activity <span>→</span></button></article>
      </div>

      <article className="card activity-card"><div className="card-heading"><div><h3>Recent activity</h3><p>What's happening across your customer channels</p></div><button className="text-button" onClick={() => setShowAllActivity(!showAllActivity)}>{showAllActivity ? "Show less" : "View all"} <span>→</span></button></div><div className="activity-list">{activity.length === 0 ? <p style={{padding:"16px",color:"#9895a3",fontSize:12}}>No activity yet — send a test message to get started.</p> : activity.map((item) => { const custName = [item.customer?.firstName, item.customer?.lastName].filter(Boolean).join(" ") || item.customer?.phone || "Unknown"; const initials = custName.split(" ").map((w: string) => w[0]).join("").slice(0,2).toUpperCase(); const colorMap: Record<string, string> = { MESSAGE_SENT:"sky", CONVERSATION_CREATED:"peach", ORDER_PLACED:"mint", ORDER_UPDATED:"lavender", CUSTOMER_TAGGED:"peach", LEAD_SCORED:"lavender" }; const statusMap: Record<string, string> = { MESSAGE_SENT:"Message in", CONVERSATION_CREATED:"New conv", ORDER_PLACED:"Order placed", ORDER_UPDATED:"Order updated", CUSTOMER_TAGGED:"New lead", LEAD_SCORED:"Score updated" }; const diff = Date.now() - new Date(item.createdAt).getTime(); const t = diff < 60000 ? "now" : diff < 3600000 ? `${Math.floor(diff/60000)}m` : diff < 86400000 ? `${Math.floor(diff/3600000)}h` : `${Math.floor(diff/86400000)}d`; return <div className="activity-row" key={item.id}><span className={`avatar ${colorMap[item.type]??""}`}>{initials}</span><div className="activity-person"><strong>{custName}</strong><span>{item.summary}</span></div><span className="channel">WA</span><span className="activity-status">{statusMap[item.type]??item.type}</span><time>{t}</time></div>; })}</div></article>
    </AppShell>
  );
}
