"use client";
import { useState } from "react";
import { AppShell } from "../../components/app-shell";

const contacts = [{ name: "Aarav Kapoor", detail: "What is included in the annual plan?", time: "2m", initials: "AK" }, { name: "Maya Iyer", detail: "Can I book a demo?", time: "18m", initials: "MI" }, { name: "Dev Malhotra", detail: "Thanks, I will check this.", time: "1h", initials: "DM" }];
export default function InboxPage() {
  const [selected, setSelected] = useState(0); const [draft, setDraft] = useState(""); const [messages, setMessages] = useState(["Hi Aarav, happy to help. The annual plan includes onboarding, priority support, and all standard features.", "What is included in the annual plan?"]);
  function makeDraft() { setDraft("The annual plan includes full access to the platform, guided onboarding, and priority support. Would you like me to share the current pricing options?"); }
  return <AppShell title="Inbox" subtitle="One place for every customer conversation."><div className="inbox-layout"><aside className="conversation-list"><div className="inbox-search">Search conversations</div>{contacts.map((contact, index) => <button key={contact.name} className={selected === index ? "conversation selected" : "conversation"} onClick={() => setSelected(index)}><b>{contact.initials}</b><span><strong>{contact.name}</strong><small>{contact.detail}</small></span><time>{contact.time}</time></button>)}</aside><section className="conversation-panel"><header><div><b>{contacts[selected].name}</b><small><i /> Active on WhatsApp</small></div><button className="filter-button">Customer profile</button></header><div className="message-stream"><div className="bubble outbound">{messages[0]}</div><div className="bubble inbound">{messages[1]}</div>{draft && <div className="ai-draft"><span>AI draft</span><p>{draft}</p><button className="primary-button" onClick={() => { setMessages([draft, messages[1]]); setDraft(""); }}>Approve draft</button><button onClick={() => setDraft("")}>Discard</button></div>}</div><footer><button className="ai-draft-button" onClick={makeDraft}>Generate AI draft</button><input placeholder="Reply to customer..." /><button className="send-button">Send</button></footer></section></div></AppShell>;
}
