import { LegalPage, LEGAL_ENTITY_NAME, LEGAL_CONTACT_EMAIL } from "../../components/legal-page";

export const metadata = { title: "Terms of Service — Relay" };

export default function TermsOfServicePage() {
  return (
    <LegalPage title="Terms of Service">
      <p>These Terms of Service ("Terms") govern access to and use of Relay, operated by {LEGAL_ENTITY_NAME}
      ("Relay", "we"). By creating a Relay account, you ("Merchant") agree to these Terms.</p>

      <h2>1. The service</h2>
      <p>Relay connects a Merchant's WhatsApp Business, Instagram, and/or email channels to an AI-assisted sales
      and support workflow: answering customer questions, taking orders, collecting payment via Razorpay, and
      surfacing conversations/orders/analytics in a merchant dashboard.</p>

      <h2>2. Merchant responsibilities</h2>
      <ul>
        <li>You are responsible for the accuracy of your product catalogue, pricing, and stock levels shown to
          customers.</li>
        <li>You must have the right to message the customers who contact you, and to use the channel accounts
          (WhatsApp Business Account, Instagram Page) you connect to Relay.</li>
        <li>You are responsible for complying with Meta's WhatsApp/Instagram platform policies and applicable
          consumer-protection, tax, and data-protection law for your own business.</li>
        <li>Autonomous AI replies and order placement are enabled by default at signup; you may configure
          approval thresholds (e.g. orders above a set value require manual approval) in Settings.</li>
      </ul>

      <h2>3. Payments</h2>
      <p>Where a Merchant enables online payment collection, payments are processed by Razorpay under Razorpay's
      own terms. Relay is not a party to the payment itself and does not hold customer funds.</p>

      <h2>4. AI-generated content</h2>
      <p>Replies, recommendations, and order summaries may be generated by an AI model grounded in your own
      catalogue and order data. While Relay is designed so the AI never invents pricing, stock, or order status,
      you remain responsible for reviewing and correcting your own catalogue data, and for any conversation you
      choose to take over manually.</p>

      <h2>5. Account suspension</h2>
      <p>We may suspend or terminate an account that violates these Terms, Meta's platform policies, Razorpay's
      terms, or applicable law, or that we reasonably believe poses a security risk to Relay or other Merchants.</p>

      <h2>6. Disclaimers and liability</h2>
      <p>The service is provided "as is". To the maximum extent permitted by law, Relay is not liable for
      indirect, incidental, or consequential damages arising from use of the service, including losses arising
      from third-party channel or payment provider outages.</p>

      <h2>7. Changes</h2>
      <p>We may update these Terms from time to time. Continued use of Relay after a change constitutes
      acceptance of the updated Terms.</p>

      <h2>8. Contact</h2>
      <p>Questions about these Terms can be sent to{" "}
      <a href={`mailto:${LEGAL_CONTACT_EMAIL}`} style={{ color: "var(--purple)" }}>{LEGAL_CONTACT_EMAIL}</a>.</p>
    </LegalPage>
  );
}
